### PR TITLE
 Add config for gluttony charm so users can add/block additional food items.

### LINKED ISSUE #223: [Feature Request] Compatibility with Mekanism Canteen
Compatibility with Mekanism's Canteen of nutrient paste and the Gluttony Charm would be fantastic.

### PR DESCRIPTION
**Pull request by iTitus**
Closes #223

This also updates Forge so that I could test this with the newest Mekanism.

The config looks like this per default:
```toml
[gluttonyCharm]
	#The registry names of food items that the Gluttony Charm should NOT consider valid food.
	blockedFoodItems = []
	#The registry names of additional items that the Gluttony Charm should consider valid food.
	additionalFoodItems = ["mekanism:canteen"]
```

Sorry about the indentation in the `build.gradle`. It is not consistent across the file and IntelliJ gets confused.

### CODE REVIEW

**Comment by iTitus** [comment]
This is also a start for #213

**Comment by Darkhax** [comment]
Thanks, I spoke to the mek devs about a way to get official support working but I forgot what we said. Planning to reach out again in a bit. I do like the config option though.

**Comment by Darkhax** [comment]
Ultimately decided to fix this by just allowing drinks to be used, this is based on the use action of the item. So potions are also fixed. https://github.com/Darkhax-Minecraft/Dark-Utilities/commit/b6a4af39fb845a78a7db3d37f3981240df610f0f

**Comment by iTitus** [comment]
Nice!

**Pull request closed without merging**
