### PR TITLE
Sneaky blocks now handle colors and bounding boxes

### PR DESCRIPTION
**Pull request by nikita488**

### CODE REVIEW

**Comment by darkhax** [comment]
Seems good, however the bounding box support will have unintended consequences. For example, the sneaky pressure plate will let the player fall through it, same deal with the sneaky torch and sneaky lever. This is why there is no support for them yet. 

Also, with the Color, it would be nice if the default modifier was white rather than black.

**Comment by nikita488** [comment]
Also i trying to find a solution to fix this (glass sides rendering):

But i don't really understand how to fix this, but i have one strange idea to replace surrounding blocks with fake blocks...

**Comment by darkhax** [comment]
There is a method in Block called `shouldSideBeRendered` which does exactly as described. You can use it to prevent faces of the block from rendering. Glass already overrides this method to add it's own logic. You could implement your own version of the code in BlockBreakable or delegate the call to the held state.

**Comment by darkhax** [comment]
Hey there, I am planning to push an update soon enough. Any update on this PR?

**Comment by nikita488** [comment]
I deleted bb support and changed default color. I still don't fix side rendering issue, cause i don't have time. I think you can merge this?

**Comment by darkhax** [comment]
Okay, didn't want to merge it prematurely.

**Pull request merged**
